/** Plain-English names for the HateCheck functional test types (Röttger et al., 2021). */
export const FUNCTIONALITY: Record<string, { name: string; group: string }> = {
  derog_neg_emote_h: { name: 'Strong negative feelings about a group', group: 'Derogation' },
  derog_neg_attrib_h: { name: 'Describes a group with negative traits', group: 'Derogation' },
  derog_dehum_h: { name: 'Dehumanises a group', group: 'Derogation' },
  derog_impl_h: { name: 'Implicit hate, no obvious bad words', group: 'Derogation' },
  threat_dir_h: { name: 'Direct threat against a group', group: 'Threats' },
  threat_norm_h: { name: 'Says threats against a group are fine', group: 'Threats' },
  slur_h: { name: 'Uses a slur', group: 'Slurs' },
  slur_homonym_nh: { name: 'Word that sounds like a slur, used innocently', group: 'Slurs' },
  slur_reclaimed_nh: { name: 'Reclaimed slur used by the group itself', group: 'Slurs' },
  profanity_h: { name: 'Hate with swearing', group: 'Profanity' },
  profanity_nh: { name: 'Swearing without hate', group: 'Profanity' },
  ref_subs_clause_h: { name: 'Hate that refers back with a pronoun', group: 'Pronouns' },
  ref_subs_sent_h: { name: 'Hate that refers back across sentences', group: 'Pronouns' },
  negate_pos_h: { name: 'Hate written as a negated compliment', group: 'Negation' },
  negate_neg_nh: { name: 'Negated hate', group: 'Negation' },
  phrase_question_h: { name: 'Hate phrased as a question', group: 'Phrasing' },
  phrase_opinion_h: { name: 'Hate phrased as an opinion', group: 'Phrasing' },
  ident_neutral_nh: { name: 'Neutral identity mention', group: 'Identity' },
  ident_pos_nh: { name: 'Positive identity mention', group: 'Identity' },
  counter_quote_nh: { name: 'Quotes hate to criticise it', group: 'Counter-speech' },
  counter_ref_nh: { name: 'Refers to hate to criticise it', group: 'Counter-speech' },
  target_obj_nh: { name: 'Abuse aimed at an object', group: 'Other targets' },
  target_indiv_nh: { name: 'Abuse aimed at one person, not a group', group: 'Other targets' },
  target_group_nh: { name: 'Abuse aimed at a non-protected group', group: 'Other targets' },
  spell_char_swap_h: { name: 'Hate with swapped letters', group: 'Spelling tricks' },
  spell_char_del_h: { name: 'Hate with missing letters', group: 'Spelling tricks' },
  spell_space_del_h: { name: 'Hate with missing spaces', group: 'Spelling tricks' },
  spell_space_add_h: { name: 'Hate with added spaces', group: 'Spelling tricks' },
  spell_leet_h: { name: 'Hate in leetspeak (h4te)', group: 'Spelling tricks' },
}
